package cowrie

import (
	"errors"
	"os"
	"path/filepath"
	"testing"
)

// TestCrossLanguageCompatibility verifies Go can correctly decode
// test vectors generated by the C implementation.
func TestCrossLanguageCompatibility(t *testing.T) {
	testdataDir := "testdata"

	t.Run("tensor_2x3_f32", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "tensor_2x3_f32.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeTensor {
			t.Fatalf("expected TypeTensor, got %v", v.Type())
		}
		tensor := v.Tensor()
		if tensor.DType != DTypeFloat32 {
			t.Errorf("dtype: expected Float32, got %v", tensor.DType)
		}
		if len(tensor.Dims) != 2 || tensor.Dims[0] != 2 || tensor.Dims[1] != 3 {
			t.Errorf("dims: expected [2, 3], got %v", tensor.Dims)
		}
		if len(tensor.Data) != 24 {
			t.Errorf("data length: expected 24, got %d", len(tensor.Data))
		}
		for i := 0; i < 24; i++ {
			if tensor.Data[i] != byte(i) {
				t.Errorf("data[%d]: expected %d, got %d", i, i, tensor.Data[i])
			}
		}
	})

	// SPEC-v1 §2.3 freeze-blocker #2: TensorRef(0x21), Image(0x22), Audio(0x23)
	// are RESERVED — decoding these legacy fixtures now rejects with
	// ERR_RESERVED_TAG instead of producing a value.
	t.Run("tensor_ref", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "tensor_ref.cowrie")
		if _, err := Decode(data); !errors.As(err, new(*TagError)) {
			t.Fatalf("expected ERR_RESERVED_TAG (*TagError), got %v", err)
		}
	})

	t.Run("image_jpeg_640x480", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "image_jpeg_640x480.cowrie")
		if _, err := Decode(data); !errors.As(err, new(*TagError)) {
			t.Fatalf("expected ERR_RESERVED_TAG (*TagError), got %v", err)
		}
	})

	t.Run("audio_pcm16_44100_stereo", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "audio_pcm16_44100_stereo.cowrie")
		if _, err := Decode(data); !errors.As(err, new(*TagError)) {
			t.Fatalf("expected ERR_RESERVED_TAG (*TagError), got %v", err)
		}
	})

	t.Run("object_with_tensor", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "object_with_tensor.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeObject {
			t.Fatalf("expected TypeObject, got %v", v.Type())
		}
		emb := v.Get("embedding")
		if emb == nil || emb.Type() != TypeTensor {
			t.Error("expected embedding to be tensor")
		}
		name := v.Get("name")
		if name == nil || name.String() != "test" {
			t.Error("expected name to be 'test'")
		}
		score := v.Get("score")
		if score == nil || score.Type() != TypeFloat64 {
			t.Error("expected score to be float64")
		}
	})

	t.Run("array_mixed_v21", func(t *testing.T) {
		// This fixture's array contains a reserved Image(0x22), so the whole
		// message now rejects with ERR_RESERVED_TAG.
		data := readTestVector(t, testdataDir, "array_mixed_v21.cowrie")
		if _, err := Decode(data); !errors.As(err, new(*TagError)) {
			t.Fatalf("expected ERR_RESERVED_TAG (*TagError), got %v", err)
		}
	})
}

func readTestVector(t *testing.T, dir, name string) []byte {
	path := filepath.Join(dir, name)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read test vector %s: %v", path, err)
	}
	return data
}

// TestGenerateCrossLanguageFixtures generates the fixture files needed by
// TestCrossLanguageCompatibility. Run once with GENERATE_COMPAT=1.
func TestGenerateCrossLanguageFixtures(t *testing.T) {
	if os.Getenv("GENERATE_COMPAT") != "1" {
		t.Skip("Set GENERATE_COMPAT=1 to generate fixtures")
	}

	dir := "testdata"
	os.MkdirAll(dir, 0755)

	fixtures := map[string]*Value{
		"tensor_2x3_f32": Tensor(DTypeFloat32, []uint64{2, 3}, func() []byte {
			data := make([]byte, 24)
			for i := range data {
				data[i] = byte(i)
			}
			return data
		}()),
		"tensor_ref": TensorRef(7, []byte{0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE}),
		"image_jpeg_640x480": Image(ImageFormatJPEG, 640, 480,
			[]byte{0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46}),
		"audio_pcm16_44100_stereo": Audio(AudioEncodingPCMInt16, 44100, 2,
			[]byte{0x00, 0x01, 0x02, 0x03}),
		"object_with_tensor": Object(
			Member{Key: "embedding", Value: Tensor(DTypeFloat32, []uint64{4}, []byte{0, 0, 0, 0, 0, 0, 128, 63, 0, 0, 0, 64, 0, 0, 64, 64})},
			Member{Key: "name", Value: String("test")},
			Member{Key: "score", Value: Float64(3.14)},
		),
		"array_mixed_v21": Array(
			Tensor(DTypeInt8, []uint64{4}, []byte{1, 2, 3, 4}),
			Image(ImageFormatJPEG, 100, 100, []byte("jpeg")),
			String("mixed"),
		),
	}

	for name, v := range fixtures {
		encoded, err := Encode(v)
		if err != nil {
			t.Fatalf("encode %s: %v", name, err)
		}
		path := filepath.Join(dir, name+".cowrie")
		if err := os.WriteFile(path, encoded, 0644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
		t.Logf("generated %s (%d bytes)", path, len(encoded))
	}
}

// TestGoToCCompatibility verifies that Go-encoded data can be decoded by C.
// This generates test vectors in a format that C can verify.
func TestGoToCCompatibility(t *testing.T) {
	testdataDir := "testdata"

	// Ensure testdata directory exists
	if err := os.MkdirAll(testdataDir, 0755); err != nil {
		t.Fatalf("failed to create testdata dir: %v", err)
	}

	// Generate Go test vectors that C can verify. reserved=true entries use a
	// SPEC-v1 §2.3 reserved tag: encode still works but our own decoder now
	// rejects them with ERR_RESERVED_TAG.
	vectors := []struct {
		name     string
		val      *Value
		reserved bool
	}{
		{"go_tensor", Tensor(DTypeFloat32, []uint64{2, 3}, func() []byte {
			data := make([]byte, 24)
			for i := range data {
				data[i] = byte(i)
			}
			return data
		}()), false},
		{"go_tensor_ref", TensorRef(7, []byte{0xDE, 0xAD, 0xBE, 0xEF}), true},
		{"go_image", Image(ImageFormatPNG, 800, 600, []byte("fake png")), true},
		{"go_audio", Audio(AudioEncodingOPUS, 48000, 2, []byte("fake opus")), true},
	}

	for _, vec := range vectors {
		name, v := vec.name, vec.val
		encoded, err := Encode(v)
		if err != nil {
			t.Fatalf("failed to encode %s: %v", name, err)
		}

		path := filepath.Join(testdataDir, name+".cowrie")
		if err := os.WriteFile(path, encoded, 0644); err != nil {
			t.Fatalf("failed to write %s: %v", path, err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(encoded))

		// Verify decode behavior of our own output.
		decoded, err := Decode(encoded)
		if vec.reserved {
			if !errors.As(err, new(*TagError)) {
				t.Errorf("%s: expected ERR_RESERVED_TAG (*TagError), got %v", name, err)
			}
			continue
		}
		if err != nil {
			t.Fatalf("failed to decode own %s: %v", name, err)
		}
		if decoded.Type() != v.Type() {
			t.Errorf("%s: type mismatch after round-trip", name)
		}
	}
}
