package cowrie

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestCrossLanguageCompatibility verifies Go can correctly decode
// test vectors generated by the C implementation.
func TestCrossLanguageCompatibility(t *testing.T) {
	testdataDir := "testdata"

	t.Run("tensor_2x3_f32", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "tensor_2x3_f32.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeTensor {
			t.Fatalf("expected TypeTensor, got %v", v.Type())
		}
		tensor := v.Tensor()
		if tensor.DType != DTypeFloat32 {
			t.Errorf("dtype: expected Float32, got %v", tensor.DType)
		}
		if len(tensor.Dims) != 2 || tensor.Dims[0] != 2 || tensor.Dims[1] != 3 {
			t.Errorf("dims: expected [2, 3], got %v", tensor.Dims)
		}
		if len(tensor.Data) != 24 {
			t.Errorf("data length: expected 24, got %d", len(tensor.Data))
		}
		for i := 0; i < 24; i++ {
			if tensor.Data[i] != byte(i) {
				t.Errorf("data[%d]: expected %d, got %d", i, i, tensor.Data[i])
			}
		}
	})

	t.Run("tensor_ref", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "tensor_ref.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeTensorRef {
			t.Fatalf("expected TypeTensorRef, got %v", v.Type())
		}
		ref := v.TensorRef()
		if ref.StoreID != 7 {
			t.Errorf("storeID: expected 7, got %d", ref.StoreID)
		}
		expectedKey := []byte{0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE, 0xBA, 0xBE}
		if !bytes.Equal(ref.Key, expectedKey) {
			t.Errorf("key: expected %x, got %x", expectedKey, ref.Key)
		}
	})

	t.Run("image_jpeg_640x480", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "image_jpeg_640x480.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeImage {
			t.Fatalf("expected TypeImage, got %v", v.Type())
		}
		img := v.Image()
		if img.Format != ImageFormatJPEG {
			t.Errorf("format: expected JPEG, got %v", img.Format)
		}
		if img.Width != 640 || img.Height != 480 {
			t.Errorf("dimensions: expected 640x480, got %dx%d", img.Width, img.Height)
		}
		expectedData := []byte{0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46}
		if !bytes.Equal(img.Data, expectedData) {
			t.Errorf("data mismatch")
		}
	})

	t.Run("audio_pcm16_44100_stereo", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "audio_pcm16_44100_stereo.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeAudio {
			t.Fatalf("expected TypeAudio, got %v", v.Type())
		}
		audio := v.Audio()
		if audio.Encoding != AudioEncodingPCMInt16 {
			t.Errorf("encoding: expected PCMInt16, got %v", audio.Encoding)
		}
		if audio.SampleRate != 44100 {
			t.Errorf("sampleRate: expected 44100, got %d", audio.SampleRate)
		}
		if audio.Channels != 2 {
			t.Errorf("channels: expected 2, got %d", audio.Channels)
		}
	})

	t.Run("adjlist_3node_4edge", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "adjlist_3node_4edge.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeAdjlist {
			t.Fatalf("expected TypeAdjlist, got %v", v.Type())
		}
		adj := v.Adjlist()
		if adj.IDWidth != IDWidthInt32 {
			t.Errorf("idWidth: expected Int32, got %v", adj.IDWidth)
		}
		if adj.NodeCount != 3 {
			t.Errorf("nodeCount: expected 3, got %d", adj.NodeCount)
		}
		if adj.EdgeCount != 4 {
			t.Errorf("edgeCount: expected 4, got %d", adj.EdgeCount)
		}
		expectedOffsets := []uint64{0, 2, 3, 4}
		for i, offset := range expectedOffsets {
			if adj.RowOffsets[i] != offset {
				t.Errorf("rowOffsets[%d]: expected %d, got %d", i, offset, adj.RowOffsets[i])
			}
		}
	})

	t.Run("rich_text_with_tokens_spans", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "rich_text_with_tokens_spans.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeRichText {
			t.Fatalf("expected TypeRichText, got %v", v.Type())
		}
		rt := v.RichText()
		if rt.Text != "Hello, world!" {
			t.Errorf("text: expected 'Hello, world!', got %q", rt.Text)
		}
		expectedTokens := []int32{101, 7592, 1010, 2088, 999, 102}
		if len(rt.Tokens) != len(expectedTokens) {
			t.Errorf("tokens length: expected %d, got %d", len(expectedTokens), len(rt.Tokens))
		} else {
			for i, tok := range expectedTokens {
				if rt.Tokens[i] != tok {
					t.Errorf("tokens[%d]: expected %d, got %d", i, tok, rt.Tokens[i])
				}
			}
		}
		if len(rt.Spans) != 2 {
			t.Errorf("spans length: expected 2, got %d", len(rt.Spans))
		}
		if rt.Spans[0].Start != 0 || rt.Spans[0].End != 5 || rt.Spans[0].KindID != 1 {
			t.Errorf("spans[0]: expected {0, 5, 1}, got %+v", rt.Spans[0])
		}
		if rt.Spans[1].Start != 7 || rt.Spans[1].End != 12 || rt.Spans[1].KindID != 2 {
			t.Errorf("spans[1]: expected {7, 12, 2}, got %+v", rt.Spans[1])
		}
	})

	t.Run("rich_text_plain", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "rich_text_plain.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		rt := v.RichText()
		if rt.Text != "Just plain text" {
			t.Errorf("text: expected 'Just plain text', got %q", rt.Text)
		}
		if rt.Tokens != nil {
			t.Errorf("expected nil tokens")
		}
		if rt.Spans != nil {
			t.Errorf("expected nil spans")
		}
	})

	t.Run("delta_3ops", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "delta_3ops.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeDelta {
			t.Fatalf("expected TypeDelta, got %v", v.Type())
		}
		delta := v.Delta()
		if delta.BaseID != 999 {
			t.Errorf("baseID: expected 999, got %d", delta.BaseID)
		}
		if len(delta.Ops) != 3 {
			t.Fatalf("ops length: expected 3, got %d", len(delta.Ops))
		}
		if delta.Ops[0].OpCode != DeltaOpSetField || delta.Ops[0].Value.String() != "updated" {
			t.Errorf("op[0]: expected SetField with 'updated'")
		}
		if delta.Ops[1].OpCode != DeltaOpDeleteField {
			t.Errorf("op[1]: expected DeleteField")
		}
		if delta.Ops[2].OpCode != DeltaOpAppendArray || delta.Ops[2].Value.Int64() != 42 {
			t.Errorf("op[2]: expected AppendArray with 42")
		}
	})

	t.Run("object_with_tensor", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "object_with_tensor.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeObject {
			t.Fatalf("expected TypeObject, got %v", v.Type())
		}
		emb := v.Get("embedding")
		if emb == nil || emb.Type() != TypeTensor {
			t.Error("expected embedding to be tensor")
		}
		name := v.Get("name")
		if name == nil || name.String() != "test" {
			t.Error("expected name to be 'test'")
		}
		score := v.Get("score")
		if score == nil || score.Type() != TypeFloat64 {
			t.Error("expected score to be float64")
		}
	})

	t.Run("array_mixed_v21", func(t *testing.T) {
		data := readTestVector(t, testdataDir, "array_mixed_v21.cowrie")
		v, err := Decode(data)
		if err != nil {
			t.Fatalf("decode failed: %v", err)
		}
		if v.Type() != TypeArray {
			t.Fatalf("expected TypeArray, got %v", v.Type())
		}
		if v.Len() != 3 {
			t.Fatalf("array length: expected 3, got %d", v.Len())
		}
		if v.Index(0).Type() != TypeTensor {
			t.Errorf("arr[0]: expected TypeTensor, got %v", v.Index(0).Type())
		}
		if v.Index(1).Type() != TypeImage {
			t.Errorf("arr[1]: expected TypeImage, got %v", v.Index(1).Type())
		}
		if v.Index(2).Type() != TypeString || v.Index(2).String() != "mixed" {
			t.Errorf("arr[2]: expected string 'mixed'")
		}
	})
}

func readTestVector(t *testing.T, dir, name string) []byte {
	path := filepath.Join(dir, name)
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("failed to read test vector %s: %v", path, err)
	}
	return data
}

// TestGoToCCompatibility verifies that Go-encoded data can be decoded by C.
// This generates test vectors in a format that C can verify.
func TestGoToCCompatibility(t *testing.T) {
	testdataDir := "testdata"

	// Ensure testdata directory exists
	if err := os.MkdirAll(testdataDir, 0755); err != nil {
		t.Fatalf("failed to create testdata dir: %v", err)
	}

	// Generate Go test vectors that C can verify
	vectors := map[string]*Value{
		"go_tensor": Tensor(DTypeFloat32, []uint64{2, 3}, func() []byte {
			data := make([]byte, 24)
			for i := range data {
				data[i] = byte(i)
			}
			return data
		}()),
		"go_tensor_ref": TensorRef(7, []byte{0xDE, 0xAD, 0xBE, 0xEF}),
		"go_image":      Image(ImageFormatPNG, 800, 600, []byte("fake png")),
		"go_audio":      Audio(AudioEncodingOPUS, 48000, 2, []byte("fake opus")),
		"go_rich_text":  RichText("Go says hello!", []int32{1, 2, 3}, []RichTextSpan{{0, 2, 1}}),
		"go_delta":      Delta(100, []DeltaOp{{DeltaOpSetField, 0, String("from_go")}}),
	}

	for name, v := range vectors {
		encoded, err := Encode(v)
		if err != nil {
			t.Fatalf("failed to encode %s: %v", name, err)
		}

		path := filepath.Join(testdataDir, name+".cowrie")
		if err := os.WriteFile(path, encoded, 0644); err != nil {
			t.Fatalf("failed to write %s: %v", path, err)
		}
		t.Logf("wrote %s (%d bytes)", path, len(encoded))

		// Verify we can decode our own output
		decoded, err := Decode(encoded)
		if err != nil {
			t.Fatalf("failed to decode own %s: %v", name, err)
		}
		if decoded.Type() != v.Type() {
			t.Errorf("%s: type mismatch after round-trip", name)
		}
	}
}
